poses:
    first_floor:
        outside_elevator: # initial_pose
            x: -21.711
            y: -0.941
            Y: -0.972
        inside_elevator_first_try:
            x: -20.917
            y: -3.368
            Y: -1.591
        inside_elevator_second_try: # same as - /exit_elevator.yaml poses: first_floor: inside_elevator:
            x: -20.875
            y: -3.155
            Y: 2.749
    second_floor:
        outside_elevator: # initial_pose
            x: -21.711
            y: -0.941
            Y: -0.972
        inside_elevator_first_try:
            x: -20.917
            y: -3.368
            Y: -1.591
        inside_elevator_second_try: # same as - /exit_elevator.yaml poses: second_floor: inside_elevator:
            x: -20.875
            y: -3.155
            Y: 2.749
