maps:
    first_floor: "/home/tal/catkin_ws/src/elevator_services/map/sim_first_floor_new.yaml"
    second_floor: "/home/tal/catkin_ws/src/elevator_services/map/simulation_map_second_floor2.yaml"
poses:
    first_floor:
        inside_elevator: # initial_pose. same as - /elevator_entrance.yaml poses: first_floor: inside_elevator_second_try:
            x: -8.924
            y: 0.152
            Y: 0
        outside_elevator: 
            x: -6.466
            y: 0.15
            Y: 0
    second_floor:
        inside_elevator: # initial_pose. same as - /elevator_entrance.yaml poses: second_floor: inside_elevator_second_try:
            x: 5.657
            y: 6.712
            Y: -0.343
        outside_elevator:
            x: 5.366
            y: 3.685
            Y: -1.672
