maps:
    first_floor: "/home/armadillo/catkin_ws/src/elevator_services/map/simulation_map_first_floor1.yaml"
    second_floor: "/home/armadillo/catkin_ws/src/elevator_services/map/simulation_map_second_floor2.yaml"

poses:
    first_floor:
        inside_elevator: # initial_pose. same as - /elevator_entrance.yaml poses: first_floor: inside_elevator_second_try:
            x: -8.65 #-8.924 -8.724
            y: 0.12 # 0.152
            Y: 0
        outside_elevator: 
            x: -5.595 
            y: -2.821
            Y: 0
    second_floor:
        inside_elevator: # initial_pose. same as - /elevator_entrance.yaml poses: second_floor: inside_elevator_second_try:
            x: 5.657
            y: 6.712
            Y: -0.343
        outside_elevator:
            x: 5.366
            y: 3.685
            Y: -1.672
